///////////////////////////////////////////////////////////
//  AIMaps.cs
//  Implementation of the Class AIMaps
//  Generated by Enterprise Architect
//  Created on:      21-mar-2008 19:30:30
//  Original author: piotrw
///////////////////////////////////////////////////////////




using SimpleAI;
using System.Collections.Generic;
namespace SimpleAI {
	public class AIMaps : IAISequencer {

        protected static int iSequNumber = 0;
        private List<AIMap> maps;

        public int Count
        {
            get { return maps.Count; }
        }

        public AIMap this[int index]
        {
            get
            {
                return maps[index];
            }
        }

		public AIMaps(){
            maps = new List<AIMap>();
		}

		~AIMaps(){

		}

        public void Add(ref AIMap newMap)
        {
            int newMapId = NextSequenceNumber;
            if (newMap.Name == "" || newMap.Name == null)
            {
                newMap.Name = "AIMap #" + newMap.Name;
            }
            maps.Add(newMap);
        }

		public virtual void Dispose(){

		}

		public int NextSequenceNumber{
			get
            {
                return ++iSequNumber;
			}
		}

	}//end AIMaps

}//end namespace SimpleAI