///////////////////////////////////////////////////////////
//  AICell.cs
//  Implementation of the Class AICell
//  Generated by Enterprise Architect
//  Created on:      21-mar-2008 20:44:42
//  Original author: piotrw
///////////////////////////////////////////////////////////




using Microsoft.Xna.Framework;
namespace SimpleAI {
	public class AINode {


		private AIMap parent;
		private int type;
        private int x;
        private int y;
        private Vector3 position;


        public Vector3 Position
        {
            get { return position; }
            set { position = value; }
        }

        
        public int X
        {
            get { return x; }
            set { x = value; }
        }


        public int Y
        {
            get { return y; }
            set { y = value; }
        }


        public int Type
        {
            get { return type; }
            set { type = value; }
        }


        public AIMap Parent
        {
            get { return parent; }
            set { parent = value; }
        }


		public AINode(){

		}

		~AINode(){

		}

		public virtual void Dispose(){

		}

	}//end AICell

}//end namespace SimpleAI