///////////////////////////////////////////////////////////
//  AIPath.cs
//  Implementation of the Class AIPath
//  Generated by Enterprise Architect
//  Created on:      20-mar-2008 20:30:16
//  Original author: piotrw
///////////////////////////////////////////////////////////




namespace SimpleAI {
	public class AIPath {

		public AIPath(){

		}

		~AIPath(){

		}

		public virtual void Dispose(){

		}

	}//end AIPath

}//end namespace SimpleAI