///////////////////////////////////////////////////////////
//  IAINameOwner.cs
//  Implementation of the Interface IAINameOwner
//  Generated by Enterprise Architect
//  Created on:      20-mar-2008 23:45:52
//  Original author: piotrw
///////////////////////////////////////////////////////////




namespace SimpleAI {
	public interface IAINameOwner {

        string Name
        {
            get;
            set;
        }
	}//end IAINameOwner

}//end namespace SimpleAI