///////////////////////////////////////////////////////////
//  IAISequencer.cs
//  Implementation of the Interface IAISequencer
//  Generated by Enterprise Architect
//  Created on:      20-mar-2008 22:59:03
//  Original author: piotrw
///////////////////////////////////////////////////////////




namespace SimpleAI {
	public interface IAISequencer {

        int NextSequenceNumber
        {
            get;
        }

	}//end IAISequencer

}//end namespace SimpleAI